# Generated by Django 4.1.7 on 2023-03-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='pollingunit_uniqueid',
            field=models.IntegerField(max_length=11, unique=True),
        ),
    ]
