# Generated by Django 4.1.7 on 2023-03-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModels', '0002_alter_agent_pollingunit_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='pollingunit_uniqueid',
            field=models.IntegerField(max_length=11),
        ),
    ]
