# Generated by Django 4.1.7 on 2023-03-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModels', '0003_alter_agent_pollingunit_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lga',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
