# Generated by Django 4.1.7 on 2023-03-23 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbModels', '0007_alter_announced_lga_results_date_entered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lga',
            name='date_entered',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
