# Generated by Django 4.1.7 on 2023-03-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModels', '0011_alter_lga_date_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='ward_id',
            field=models.IntegerField(max_length=11),
        ),
    ]
