# Generated by Django 4.1.7 on 2023-03-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbModels', '0013_alter_announced_lga_results_date_entered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polling_unit',
            old_name='Polling_unit_id',
            new_name='polling_unit_id',
        ),
    ]
