# Generated by Django 4.1.7 on 2023-03-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModels', '0014_rename_polling_unit_id_polling_unit_polling_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling_unit',
            name='polling_unit_number',
            field=models.CharField(max_length=50),
        ),
    ]
