# Generated by Django 4.1.7 on 2023-03-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModels', '0015_alter_polling_unit_polling_unit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling_unit',
            name='unique_ward_id',
            field=models.IntegerField(),
        ),
    ]
