# Generated by Django 4.1.7 on 2023-03-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModels', '0017_alter_polling_unit_unique_ward_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling_unit',
            name='ward_id',
            field=models.IntegerField(blank=True),
        ),
    ]
