# Generated by Django 4.1.7 on 2023-03-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModels', '0019_alter_polling_unit_ward_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling_unit',
            name='user_ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
